steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$SHORT_SHA', 'gcr.io/$PROJECT_ID/asterisk-16-ari:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$SHORT_SHA', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/asterisk-16-ari:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/asterisk-16-ari:$BRANCH_NAME']
images:
- 'gcr.io/$PROJECT_ID/asterisk-16-ari:$BRANCH_NAME'
