version: '3'

services:
  asterisk-16-ari:
    build:
      context: .
    restart: unless-stopped
    container_name: asterisk-16-ari
    ports:
      - "5061:5061"
      - "80:80"
      - "443:443"
    environment:
      - TRUNK_TYPE
      - TRUNK_ACCOUNT
      - TRUNK_PASSWORD
      - SIP_REGISTRAR
      - ARI_USER
      - ARI_PASSWORD
      - ARI_APPLICATION
