apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asterisk
  name: asterisk
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: asterisk
  strategy:
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asterisk
    spec:
      containers:
        image: gcr.io/smbconnect/asterisk-16-ari:main
        imagePullPolicy: IfNotPresent
        name: asterisk
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: TRUNK_TYPE
          valueFrom:
            configMapKeyRef:
              key: TRUNK_TYPE
              name: smbconnect-config-mr7e
        - name: ARI_USER
          valueFrom:
            configMapKeyRef:
              key: ARI_USER
              name: smbconnect-config-mr7e
        - name: ARI_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: ARI_PASSWORD
              name: smbconnect-config-mr7e
        - name: ARI_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: ARI_APPLICATION
              name: smbconnect-config-mr7e
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
